# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clanchor < Formula
  desc "Version and distribute your CLAUDE.md files"
  homepage "https://github.com/valon-loshaj/clanchor"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.1/clanchor-darwin-amd64.tar.gz"
      sha256 "d76f2c66f07cbb722e4b9acc9264150ff67f0dadfe9f09193a946a51e27c7d64"

      define_method(:install) do
        bin.install "clanchor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.1/clanchor-darwin-arm64.tar.gz"
      sha256 "8e812d6d752873e0a44296cb7cfda77627433e9d4576179ea63a02f4852769ac"

      define_method(:install) do
        bin.install "clanchor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.1/clanchor-linux-amd64.tar.gz"
      sha256 "76c0bc133fed852459b345de526e4995b6af9798b5e9faac49269d7fb64d16bb"
      define_method(:install) do
        bin.install "clanchor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.1/clanchor-linux-arm64.tar.gz"
      sha256 "4885b9dacdbd6bc957744b04c7e650175347e73adc965216e50e534914945f57"
      define_method(:install) do
        bin.install "clanchor"
      end
    end
  end
end
