# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clanchor < Formula
  desc "Version and distribute your CLAUDE.md files"
  homepage "https://github.com/valon-loshaj/clanchor"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.0/clanchor-darwin-amd64.tar.gz"
      sha256 "6168506ea3c9eab9aaccb9ee67732898fa36c511dcaec6137b265993ae461b10"

      define_method(:install) do
        bin.install "clanchor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.0/clanchor-darwin-arm64.tar.gz"
      sha256 "9db1b1ae4b14e764a41ed8bc68250b90b048434d742b7b220902109c7ff895ac"

      define_method(:install) do
        bin.install "clanchor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.0/clanchor-linux-amd64.tar.gz"
      sha256 "d9a56814f92c6a1c3af2a273e6ef9f939f739a82e3df51fc64b54d06dae67821"
      define_method(:install) do
        bin.install "clanchor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.2.0/clanchor-linux-arm64.tar.gz"
      sha256 "dd09e1211cd3e6f356cbaa75b5bdcc96a767c49970549d66db59aae80c40764c"
      define_method(:install) do
        bin.install "clanchor"
      end
    end
  end
end
