# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clanchor < Formula
  desc "Version and distribute your CLAUDE.md files"
  homepage "https://github.com/valon-loshaj/clanchor"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.1.1/clanchor-darwin-amd64.tar.gz"
      sha256 "37412b90084a72d3139b2399b310f521158a5dcd6446746fb00501b0dc432c9f"

      define_method(:install) do
        bin.install "clanchor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.1.1/clanchor-darwin-arm64.tar.gz"
      sha256 "919b030852c8ca7844e751dae69ea227d9166d0731b87533b97d91805c589810"

      define_method(:install) do
        bin.install "clanchor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.1.1/clanchor-linux-amd64.tar.gz"
      sha256 "c0c11693f4b2f94f0cd0072dbf3b130f987c6bd7928666ba042d49cfb399ff3e"
      define_method(:install) do
        bin.install "clanchor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valon-loshaj/clanchor/releases/download/v0.1.1/clanchor-linux-arm64.tar.gz"
      sha256 "803d3b6f36f298fc2298cbdcee2a4602df654f01b8721e9e8620354ea039598e"
      define_method(:install) do
        bin.install "clanchor"
      end
    end
  end
end
